import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import type { TrelloClient } from '../../src/createTrelloClient';
import { getLiveClient } from './setup/client';
import { ResourceTracker } from './setup/resources';

describe('Notifications', () => {
  let trello!: TrelloClient;
  const tracker = new ResourceTracker();

  // Notifications are generated by external events — we use whatever exists on the account.
  let notificationId: string;
  let notificationsAvailable = false;

  // IDs for sub-resource tests — populated from whichever notification has the resource.
  let notifWithBoardId: string | undefined;
  let notifWithCardId: string | undefined;
  let notifWithMemberId: string | undefined;

  beforeAll(async () => {
    trello = getLiveClient();

    const notifications = await trello.members.getMemberNotifications({ id: 'me', limit: 50 });

    if (notifications.length === 0) return;

    notificationsAvailable = true;
    notificationId = notifications[0].id!;

    for (const n of notifications) {
      if (!notifWithBoardId && n.board?.id) notifWithBoardId = n.id;
      if (!notifWithCardId && n.card?.id) notifWithCardId = n.id;
      if (!notifWithMemberId && n.idMemberCreator) notifWithMemberId = n.id;
    }
  });

  afterAll(() => tracker.cleanup());

  // ─── retrieval ─────────────────────────────────────────────────────────────

  describe('retrieval', () => {
    it('getNotification returns a Notification with id', async ({ skip }) => {
      if (!notificationsAvailable) skip();
      const notification = await trello.notifications.getNotification({ id: notificationId });
      expect(notification.id).toBe(notificationId);
    });

    it('getNotification has an unread boolean', async ({ skip }) => {
      if (!notificationsAvailable) skip();
      const notification = await trello.notifications.getNotification({ id: notificationId });
      expect(typeof notification.unread).toBe('boolean');
    });

    it('getNotificationField returns _value for unread field', async ({ skip }) => {
      if (!notificationsAvailable) skip();
      const result = await trello.notifications.getNotificationField<boolean>({
        id: notificationId,
        field: 'unread',
      });
      expect(typeof result._value).toBe('boolean');
    });
  });

  // ─── read / unread mutation ─────────────────────────────────────────────────

  describe('read / unread', () => {
    it('updateNotification returns the updated Notification', async ({ skip }) => {
      if (!notificationsAvailable) skip();
      const updated = await trello.notifications.updateNotification({ id: notificationId, unread: false });
      expect(updated.id).toBe(notificationId);
      expect(updated.unread).toBe(false);
    });

    it('updateNotificationUnreadStatus marks the notification as unread', async ({ skip }) => {
      if (!notificationsAvailable) skip();
      const updated = await trello.notifications.updateNotificationUnreadStatus({
        id: notificationId,
        value: true,
      });
      expect(updated.id).toBe(notificationId);
      expect(updated.unread).toBe(true);
    });

    it('markAllNotificationsRead does not throw', async () => {
      await expect(trello.notifications.markAllNotificationsRead({ read: true })).resolves.not.toThrow();
    });
  });

  // ─── board ─────────────────────────────────────────────────────────────────

  describe('board', () => {
    it('getNotificationBoard returns the Board', async ({ skip }) => {
      if (!notifWithBoardId) skip();
      const board = await trello.notifications.getNotificationBoard({ id: notifWithBoardId! });
      expect(typeof board.id).toBe('string');
    });
  });

  // ─── card ──────────────────────────────────────────────────────────────────

  describe('card', () => {
    it('getNotificationCard returns the Card', async ({ skip }) => {
      if (!notifWithCardId) skip();
      const card = await trello.notifications.getNotificationCard({ id: notifWithCardId! });
      expect(typeof card.id).toBe('string');
    });
  });

  // ─── creator ───────────────────────────────────────────────────────────────

  describe('creator', () => {
    it('getNotificationCreator returns the Member who created the notification', async ({ skip }) => {
      if (!notifWithMemberId) skip();
      const member = await trello.notifications.getNotificationCreator({ id: notifWithMemberId! });
      expect(typeof member.id).toBe('string');
    });
  });

  // ─── list / member / organization (skip — uncommon notification types) ─────

  describe('list', () => {
    it('getNotificationList does not throw', async ({ skip }) => {
      skip();
    });
  });

  describe('member', () => {
    it('getNotificationMember does not throw', async ({ skip }) => {
      skip();
    });
  });

  describe('organization', () => {
    it('getNotificationOrganization does not throw', async ({ skip }) => {
      skip();
    });
  });
});
