import { z } from 'zod';
/** The fields on a Card. */

export const CardFieldsSchema = z.enum([
  'id',
  'address',
  'badges',
  'checkItemStates',
  'closed',
  'coordinates',
  'creationMethod',
  'dueComplete',
  'dateLastActivity',
  'desc',
  'descData',
  'due',
  'dueReminder',
  'idBoard',
  'idChecklists',
  'idLabels',
  'idList',
  'idMembers',
  'idMembersVoted',
  'idShort',
  'idAttachmentCover',
  'labels',
  'limits',
  'locationName',
  'manualCoverAttachment',
  'name',
  'pos',
  'shortLink',
  'shortUrl',
  'subscribed',
  'url',
  'cover',
  'isTemplate',
]);

export type CardFields = z.infer<typeof CardFieldsSchema>;
