import { z } from 'zod';
import { apiObject } from '#/core';
import { CheckItemStateSchema } from '#/models/checkItemState';
import { ChecklistSchema } from '#/models/checklist';
import { LabelSchema } from '#/models/label';
import { LimitsSchema } from '#/models/limits';
import { ColorSchema } from '#/models/color';

export const CardSchema = apiObject({
  id: z.string(),
  address: z.string().nullish(),
  badges: apiObject({
    attachmentsByType: apiObject({
      trello: apiObject({
        board: z.number().optional(),
        card: z.number().optional(),
      }).optional(),
    }).optional(),
    location: z.boolean().optional(),
    votes: z.number().optional(),
    viewingMemberVoted: z.boolean().optional(),
    subscribed: z.boolean().optional(),
    fogbugz: z.string().optional(),
    checkItems: z.number().optional(),
    checkItemsChecked: z.number().optional(),
    comments: z.number().optional(),
    attachments: z.number().optional(),
    description: z.boolean().optional(),
    due: z.coerce.date().nullish(),
    start: z.coerce.date().nullish(),
    dueComplete: z.boolean().optional(),
    checkItemsEarliestDue: z.coerce.date().nullish(),
    externalSource: z.record(z.string(), z.any()).nullish(),
    lastUpdatedByAi: z.boolean().optional(),
    maliciousAttachments: z.number().optional(),
  }).optional(),
  cardRole: z.enum(['separator', 'board', 'mirror', 'link']).nullish(),
  checkItemStates: z.array(CheckItemStateSchema).optional(),
  closed: z.boolean().optional(),
  coordinates: z.string().nullish(),
  creationMethod: z.string().nullish(),
  dateLastActivity: z.coerce.date().optional(),
  desc: z.string().optional(),
  descData: apiObject({
    emoji: z.record(z.string(), z.any()).optional(),
  }).optional(),
  due: z.coerce.date().nullish(),
  dueReminder: z.number().nullish(),
  idBoard: z.string().optional(),
  idChecklists: z.array(z.union([ChecklistSchema, z.string()])).optional(),
  idLabels: z.array(z.union([LabelSchema, z.string()])).optional(),
  idList: z.string().optional(),
  idMembers: z.array(z.string()).optional(),
  idMembersVoted: z.array(z.string()).optional(),
  idShort: z.number().optional(),
  idAttachmentCover: z.string().nullish(),
  labels: z.array(LabelSchema).optional(),
  limits: LimitsSchema.optional(),
  locationName: z.string().nullish(),
  manualCoverAttachment: z.boolean().optional(),
  mirrorSourceId: z.string().nullish(),
  name: z.string().optional(),
  pos: z.number().optional(),
  shortLink: z.string().optional(),
  shortUrl: z.string().optional(),
  subscribed: z.boolean().optional(),
  url: z.string().optional(),
  cover: apiObject({
    idAttachment: z.string().nullish(),
    color: ColorSchema.nullish(),
    idUploadedBackground: z.boolean().nullish(),
    size: z.enum(['normal']).optional(),
    brightness: z.enum(['light', 'dark']).optional(),
    isTemplate: z.boolean().optional(),
    idPlugin: z.string().nullish(),
    yPosition: z.number().optional(),
  }).optional(),
  agent: apiObject({
    name: z.string().nullish(),
    conversationId: z.string().nullish(),
  }).nullish(),
  dueComplete: z.boolean().optional(),
  email: z.string().nullish(),
  isTemplate: z.boolean().optional(),
  nodeId: z.string().optional(),
  pinned: z.boolean().optional(),
  start: z.coerce.date().nullish(),
  /** Metadata attached to the card when it was created or modified by an agent rather than a human member. */
  aiMetadata: z.unknown().optional(),
  attachments: z.array(z.unknown()).optional(),
  creationMethodError: z.unknown().optional(),
  creationMethodLoadingStartedAt: z.unknown().optional(),
  customFieldItems: z.array(z.unknown()).optional(),
  dateClosed: z.unknown().optional(),
  dateCompleted: z.unknown().optional(),
  dateViewedByCreator: z.unknown().optional(),
  externalSource: z.unknown().optional(),
  faviconUrl: z.unknown().optional(),
  idMemberCreator: z.string().nullish(),
  idOrganization: z.string().nullish(),
  manifest: z.unknown().optional(),
  members: z.array(z.unknown()).optional(),
  membersVoted: z.array(z.unknown()).optional(),
  mirrorSourceNodeId: z.unknown().optional(),
  originalDesc: z.string().nullish(),
  originalName: z.string().nullish(),
  pluginData: z.array(z.unknown()).optional(),
  recurrenceRule: z.unknown().optional(),
  singleInstrumentationId: z.unknown().optional(),
  sourceEmail: z.unknown().optional(),
  staticMapUrl: z.unknown().optional(),
  stickers: z.array(z.unknown()).optional(),
  urlSource: z.unknown().optional(),
  urlSourceText: z.unknown().optional(),
});

export type Card = z.infer<typeof CardSchema>;
