name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create .env file
        run: |
          touch .env
          echo TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }} >> .env
          echo TRELLO_API_TOKEN=${{ secrets.TRELLO_API_TOKEN }} >> .env
      - run: npm run build
      - run: npm run test
      - run: npm run lint
        env:
          CI: true
